//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillionLuxury.TechhicalTest.Resources.Validations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MillionLuxury.TechhicalTest.Resources.Validations.CommonValidationMessages", typeof(CommonValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be equal to or greater than zero..
        /// </summary>
        public static string AtributeEqualOrGreaterThanZero {
            get {
                return ResourceManager.GetString("AtributeEqualOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be greater than zero.
        /// </summary>
        public static string AtributeGreaterThanZero {
            get {
                return ResourceManager.GetString("AtributeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is invalid.
        /// </summary>
        public static string AtributeGuidEmpty {
            get {
                return ResourceManager.GetString("AtributeGuidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be a value between {1} and {2}..
        /// </summary>
        public static string AtributeInRange {
            get {
                return ResourceManager.GetString("AtributeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is required.
        /// </summary>
        public static string AtributeRequired {
            get {
                return ResourceManager.GetString("AtributeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be a date equal to or greater than current date.
        /// </summary>
        public static string DateEqualOrGreaterThanToday {
            get {
                return ResourceManager.GetString("DateEqualOrGreaterThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be a date equal to or less than current date.
        /// </summary>
        public static string DateEqualOrLessThanToday {
            get {
                return ResourceManager.GetString("DateEqualOrLessThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be a date equal to current date.
        /// </summary>
        public static string DateGreaterThanToday {
            get {
                return ResourceManager.GetString("DateGreaterThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be a date less than the current one.
        /// </summary>
        public static string DateLessThanToday {
            get {
                return ResourceManager.GetString("DateLessThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity does not exist.
        /// </summary>
        public static string EntityNotExists {
            get {
                return ResourceManager.GetString("EntityNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was generated while processing the request.
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be equal to or greater than field {1}.
        /// </summary>
        public static string FieldEqualOrGreaterThan {
            get {
                return ResourceManager.GetString("FieldEqualOrGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be greater than field {1}.
        /// </summary>
        public static string FieldGreaterThan {
            get {
                return ResourceManager.GetString("FieldGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be a maximum of {1} characters long.
        /// </summary>
        public static string FieldMaxLength {
            get {
                return ResourceManager.GetString("FieldMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is not a correct format.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was generated while completing the operation.
        /// </summary>
        public static string MessageOperationError {
            get {
                return ResourceManager.GetString("MessageOperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was generated while processing the request.
        /// </summary>
        public static string NotificationRequestError {
            get {
                return ResourceManager.GetString("NotificationRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} was not specified.
        /// </summary>
        public static string NotSpecifiedEnum {
            get {
                return ResourceManager.GetString("NotSpecifiedEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The statement has selection fields and cannot be executed. Use the GetSelect method..
        /// </summary>
        public static string QueryRequestGetDataNotValid {
            get {
                return ResourceManager.GetString("QueryRequestGetDataNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The statement cannot be executed since it has no selection fields. Use the GetData method..
        /// </summary>
        public static string QueryRequestGetSelectNotValid {
            get {
                return ResourceManager.GetString("QueryRequestGetSelectNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be less than the {1} field.
        /// </summary>
        public static string StartAtributeGraterThanEnd {
            get {
                return ResourceManager.GetString("StartAtributeGraterThanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors were detected in the filter of request.
        /// </summary>
        public static string ValidationBadQueryStringFilter {
            get {
                return ResourceManager.GetString("ValidationBadQueryStringFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while validating the entity.
        /// </summary>
        public static string ValidationEntityErrors {
            get {
                return ResourceManager.GetString("ValidationEntityErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors were generated.
        /// </summary>
        public static string ValidationExceptionMessage {
            get {
                return ResourceManager.GetString("ValidationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string ValidationNotFound {
            get {
                return ResourceManager.GetString("ValidationNotFound", resourceCulture);
            }
        }
    }
}
